### ISSUE TITLE
Unable to start the service.

### ISSUE THREAD

**Issue by RydeTech** [princelau/rydetest2021#1]
I have tried with 
`rydetest2021 % go run *.go`
`service.go:4:2: cannot find package "bitbucket.org/libertywireless/user-service/logging" in any of:
	/usr/local/go/src/bitbucket.org/libertywireless/user-service/logging (from $GOROOT)
	/Users/pirate_king/go/src/bitbucket.org/libertywireless/user-service/logging (from $GOPATH)`

and 
`rydetest2021 % go run main.go`
`# command-line-arguments
./main.go:28:20: undefined: NewUserController
./main.go:28:38: undefined: NewUserService`

But no success. Can you check your code and revert back to us. Thanks

**Comment by princelau** [comment]
Error due to import of wrong log package!
Apologies & fixed with correct log package import!
